# Generated by Django 4.2.7 on 2023-11-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traceroute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
                ('ttl', models.IntegerField()),
                ('icmp_type', models.IntegerField(null=True)),
                ('icmp_code', models.IntegerField(null=True)),
                ('remote_machine', models.CharField(max_length=50, null=True)),
                ('protocol', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
